### ISSUE TITLE
GitHubの教科書を読破する。

### ISSUE THREAD

**Issue by konpeitoure** [liveinTakabata/konpeitou.biz#1]
- [x] GitHubの教科書を読破する。
- [x] Git　集中講座を読破する。

**Comment by konpeitoure** [comment]
guratanは睡眠中

**Comment by konpeitoure** [comment]
![c9394c8e](https://user-images.githubusercontent.com/22209952/30518466-a67ddaf4-9bb9-11e7-950b-899b10b40bec.jpg)

**Comment by guratan** [comment]
マージはよ(/・ω・)/

**Comment by konpeitoure** [comment]
masterにマージ完了

**Comment by guratan** [comment]
あざーす
で私は何するの

**Comment by konpeitoure** [comment]
:smile: 
本を読む

**Comment by guratan** [comment]
いやだ
